### Variables globales
@host = http://localhost:8000

### Obtener todos los libros
GET {{host}}/libros/

### Obtener un libro específico por ID
GET {{host}}/libros/1

### Crear un nuevo libro
POST {{host}}/libros/
Content-Type: application/json

{
  "titulo": "No me puedes lastimar",
  "autor": "David Goggins",
  "isbn": "9780307474728",
  "categoria": "Autoayuda",
  "estado": "disponible"
}

### Actualizar un libro
PUT {{host}}/libros/1
Content-Type: application/json

{
  "titulo": "No mepuedes lastimar(edicion especial)",
  "estado": "en reparación"
}

### Eliminar un libro
DELETE {{host}}/libros/1

### Buscar libros
GET {{host}}/libros/buscar/?q=Márquez

### Buscar libros por categoría
GET {{host}}/libros/buscar/?categoria=Novela